<?php

/**
 * @file
 * INVENTAIRE MODULE
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\block\Entity\Block;

/**
 * Implements hook_views_pre_view().
 */
function inventaire_views_pre_view($view, $display_id, array &$args) {
  if ($view->storage->id() == 'listing_page') {
  
    $user_roles = \Drupal::currentUser()->getRoles();
    // var_dump( $user_roles); 
    /* authenticated */ 
     
    if (!in_array('administrator', $user_roles)) {
      $view->removeHandler($display_id, 'field', 'nothing');
      $view->removeHandler($display_id, 'field', 'nothing_1');
    }
  }
}

/**
 * Implements hook_theme_suggestions_alter
 */
function sqli_inventaire_theme_suggestions_alter(array &$suggestions, array $variables)
{

    if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
        $original_theme_hook = $variables['theme_hook_original'];

        $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
    }

    return $suggestions;
 
}


/**
 * Implementation of hook_theme_suggestions_form_input_alter()
 * @param $suggestions
 * @param array $variables
 */
function sqli_inventaire_theme_suggestions_input_alter(&$suggestions, array $variables) {
  $element = $variables['element'];

  if (isset($element['#attributes']['data-twig-suggestion'])) {
    $suggestions[] = 'input__' .str_replace('-', '_', $element['#type']). '__' .str_replace('-', '_', $element['#attributes']['data-twig-suggestion']);
   }
  return $suggestions;
}

/**
 * Implementation of hook_theme_suggestions_form_element_alter().
 */
function sqli_inventaire_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {
  if (\Drupal::service('path.current')->getPath() == '/user/login' )  {
    $suggestions[] = $variables['theme_hook_original'] . '__' .str_replace('-', '_', 'user-login');
  }

  if ( \Drupal::service('path.current')->getPath() == '/user/register') {
    $suggestions[] = $variables['theme_hook_original'] . '__' .str_replace('-', '_', 'user-register');
  }

  if ( \Drupal::service('path.current')->getPath() == '/user/password') {
    $suggestions[] = $variables['theme_hook_original'] . '__' .str_replace('-', '_', 'user-pass');
  }

  $element = $variables['element'];

  if (isset($element['#attributes']['data-twig-suggestion'])) {
    $suggestions[] = $variables['theme_hook_original'] .'__' .str_replace('-', '_', $element['#attributes']['data-twig-suggestion']);
   }


  return $suggestions;
}


function sqli_inventaire_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#theme'] = ['my_user_login'];
  foreach (\Drupal\Core\Render\Element::children($form) as $key) {
    $form[$key]['#attributes']['data-twig-suggestion'] = $form['#id'];
  }

  $form['actions']['submit']['#attributes']['data-twig-suggestion'] = $form['#id'];
}